### ISSUE TITLE
Map visualizations not working anymore

### ISSUE THREAD

**Issue by gardart** [gardart/amazon-mws-elastic#1]
Map visualizations not working anymore in Kibana
FIX:
https://github.com/elastic/kibana/issues/7717

WMS URL: http://ows-tile.terrestris.de/osm-basemap/service?
WMS Layers: OSM-WMS
WMS Version: 1.1.1
WMS format: image/jpeg

![2017-01-09 23_24_09-map visualizations not working anymore issue 7717 elastic_kibana](https://cloud.githubusercontent.com/assets/3597603/21787763/e624380e-d6c2-11e6-8f9d-eb14b653fea1.jpg)

**Comment by sharon-ca** [comment]
I found the same situation, does anybody have solution here?

**Comment by gardart** [comment]
I fixed this using directions described here elastic/kibana#7717 (I pasted them in above as well)

**Comment by mr337** [comment]
Followed the above and still no luck. I think the server is either down or getting hosed.

**Comment by gardart** [comment]
are you clicking on this link?
http://ows-tile.terrestris.de/osm-basemap/service?

**Comment by mr337** [comment]
Yeah and sometimes get instant response of nothing (should have checked return code), or it looks to be timing out. Here is the net log of using that WMS in Kibana.

![hung](https://cloud.githubusercontent.com/assets/413937/22746367/19dfdbd4-ede9-11e6-8e83-aa5e74eed9d7.png)

**Comment by cbarbaza** [comment]
Same issue, the configuration with  : http://ows-tile.terrestris.de/osm-basemap/service? don't workd anymore. 
Someone have another provider ?

**Comment by gardart** [comment]
Fixed in Elastic version 5.2
No need for WMS URL: http://ows-tile.terrestris.de/osm-basemap/service? anymore in kibana

**Comment by kalanityL** [comment]
For those interested in values that work without updgrading 
found [here](https://discuss.elastic.co/t/changing-map-type-wms/82106) 
http://ows.mundialis.de/services/service?
with WMS layers set to:
TOPO-OSM-WMS
